services:
  backend:
    build:
      context: ./api
    container_name: backend
    networks:
      - backend-net
      - postgres-net
    expose:
      - "8000"
      - "8001" # for external connections
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/app/healthchecker"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 10s # Give the app time to start before the first check
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DBNAME: traffic_inspector
      POSTGRES_USER: traffic_inspector
      POSTGRES_PASSWORD: password # secret not really needed rn
      POSTGRES_PORT: 5432
      API_ENDPOINT: :8000
      BACKEND_URL: http://backend:8000
      GIN_MODE: release

  nginx:
    build:
      context: ./ui
    container_name: nginx
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy # Wait for the backend to be healthy
    networks:
      - backend-net

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: traffic_inspector
      POSTGRES_USER: traffic_inspector
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-net  # only accessible to backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend-net:
    driver: bridge
  postgres-net:
    driver: bridge

volumes:
  postgres_data:

