// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/koltiradw/TrafficInspector/api/models"
)

func newWidget(db *gorm.DB, opts ...gen.DOOption) widget {
	_widget := widget{}

	_widget.widgetDo.UseDB(db, opts...)
	_widget.widgetDo.UseModel(&models.Widget{})

	tableName := _widget.widgetDo.TableName()
	_widget.ALL = field.NewAsterisk(tableName)
	_widget.I = field.NewString(tableName, "i")
	_widget.Name = field.NewString(tableName, "name")
	_widget.Config = field.NewField(tableName, "config")
	_widget.Bookmarked = field.NewBool(tableName, "bookmarked")

	_widget.fillFieldMap()

	return _widget
}

type widget struct {
	widgetDo widgetDo

	ALL        field.Asterisk
	I          field.String
	Name       field.String
	Config     field.Field
	Bookmarked field.Bool

	fieldMap map[string]field.Expr
}

func (w widget) Table(newTableName string) *widget {
	w.widgetDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w widget) As(alias string) *widget {
	w.widgetDo.DO = *(w.widgetDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *widget) updateTableName(table string) *widget {
	w.ALL = field.NewAsterisk(table)
	w.I = field.NewString(table, "i")
	w.Name = field.NewString(table, "name")
	w.Config = field.NewField(table, "config")
	w.Bookmarked = field.NewBool(table, "bookmarked")

	w.fillFieldMap()

	return w
}

func (w *widget) WithContext(ctx context.Context) IWidgetDo { return w.widgetDo.WithContext(ctx) }

func (w widget) TableName() string { return w.widgetDo.TableName() }

func (w widget) Alias() string { return w.widgetDo.Alias() }

func (w widget) Columns(cols ...field.Expr) gen.Columns { return w.widgetDo.Columns(cols...) }

func (w *widget) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *widget) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 4)
	w.fieldMap["i"] = w.I
	w.fieldMap["name"] = w.Name
	w.fieldMap["config"] = w.Config
	w.fieldMap["bookmarked"] = w.Bookmarked
}

func (w widget) clone(db *gorm.DB) widget {
	w.widgetDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w widget) replaceDB(db *gorm.DB) widget {
	w.widgetDo.ReplaceDB(db)
	return w
}

type widgetDo struct{ gen.DO }

type IWidgetDo interface {
	gen.SubQuery
	Debug() IWidgetDo
	WithContext(ctx context.Context) IWidgetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWidgetDo
	WriteDB() IWidgetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWidgetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWidgetDo
	Not(conds ...gen.Condition) IWidgetDo
	Or(conds ...gen.Condition) IWidgetDo
	Select(conds ...field.Expr) IWidgetDo
	Where(conds ...gen.Condition) IWidgetDo
	Order(conds ...field.Expr) IWidgetDo
	Distinct(cols ...field.Expr) IWidgetDo
	Omit(cols ...field.Expr) IWidgetDo
	Join(table schema.Tabler, on ...field.Expr) IWidgetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWidgetDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWidgetDo
	Group(cols ...field.Expr) IWidgetDo
	Having(conds ...gen.Condition) IWidgetDo
	Limit(limit int) IWidgetDo
	Offset(offset int) IWidgetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWidgetDo
	Unscoped() IWidgetDo
	Create(values ...*models.Widget) error
	CreateInBatches(values []*models.Widget, batchSize int) error
	Save(values ...*models.Widget) error
	First() (*models.Widget, error)
	Take() (*models.Widget, error)
	Last() (*models.Widget, error)
	Find() ([]*models.Widget, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Widget, err error)
	FindInBatches(result *[]*models.Widget, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Widget) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWidgetDo
	Assign(attrs ...field.AssignExpr) IWidgetDo
	Joins(fields ...field.RelationField) IWidgetDo
	Preload(fields ...field.RelationField) IWidgetDo
	FirstOrInit() (*models.Widget, error)
	FirstOrCreate() (*models.Widget, error)
	FindByPage(offset int, limit int) (result []*models.Widget, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWidgetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w widgetDo) Debug() IWidgetDo {
	return w.withDO(w.DO.Debug())
}

func (w widgetDo) WithContext(ctx context.Context) IWidgetDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w widgetDo) ReadDB() IWidgetDo {
	return w.Clauses(dbresolver.Read)
}

func (w widgetDo) WriteDB() IWidgetDo {
	return w.Clauses(dbresolver.Write)
}

func (w widgetDo) Session(config *gorm.Session) IWidgetDo {
	return w.withDO(w.DO.Session(config))
}

func (w widgetDo) Clauses(conds ...clause.Expression) IWidgetDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w widgetDo) Returning(value interface{}, columns ...string) IWidgetDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w widgetDo) Not(conds ...gen.Condition) IWidgetDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w widgetDo) Or(conds ...gen.Condition) IWidgetDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w widgetDo) Select(conds ...field.Expr) IWidgetDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w widgetDo) Where(conds ...gen.Condition) IWidgetDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w widgetDo) Order(conds ...field.Expr) IWidgetDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w widgetDo) Distinct(cols ...field.Expr) IWidgetDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w widgetDo) Omit(cols ...field.Expr) IWidgetDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w widgetDo) Join(table schema.Tabler, on ...field.Expr) IWidgetDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w widgetDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWidgetDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w widgetDo) RightJoin(table schema.Tabler, on ...field.Expr) IWidgetDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w widgetDo) Group(cols ...field.Expr) IWidgetDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w widgetDo) Having(conds ...gen.Condition) IWidgetDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w widgetDo) Limit(limit int) IWidgetDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w widgetDo) Offset(offset int) IWidgetDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w widgetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWidgetDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w widgetDo) Unscoped() IWidgetDo {
	return w.withDO(w.DO.Unscoped())
}

func (w widgetDo) Create(values ...*models.Widget) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w widgetDo) CreateInBatches(values []*models.Widget, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w widgetDo) Save(values ...*models.Widget) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w widgetDo) First() (*models.Widget, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Widget), nil
	}
}

func (w widgetDo) Take() (*models.Widget, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Widget), nil
	}
}

func (w widgetDo) Last() (*models.Widget, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Widget), nil
	}
}

func (w widgetDo) Find() ([]*models.Widget, error) {
	result, err := w.DO.Find()
	return result.([]*models.Widget), err
}

func (w widgetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Widget, err error) {
	buf := make([]*models.Widget, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w widgetDo) FindInBatches(result *[]*models.Widget, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w widgetDo) Attrs(attrs ...field.AssignExpr) IWidgetDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w widgetDo) Assign(attrs ...field.AssignExpr) IWidgetDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w widgetDo) Joins(fields ...field.RelationField) IWidgetDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w widgetDo) Preload(fields ...field.RelationField) IWidgetDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w widgetDo) FirstOrInit() (*models.Widget, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Widget), nil
	}
}

func (w widgetDo) FirstOrCreate() (*models.Widget, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Widget), nil
	}
}

func (w widgetDo) FindByPage(offset int, limit int) (result []*models.Widget, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w widgetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w widgetDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w widgetDo) Delete(models ...*models.Widget) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *widgetDo) withDO(do gen.Dao) *widgetDo {
	w.DO = *do.(*gen.DO)
	return w
}
