// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/koltiradw/TrafficInspector/api/models"
)

func newFlow(db *gorm.DB, opts ...gen.DOOption) flow {
	_flow := flow{}

	_flow.flowDo.UseDB(db, opts...)
	_flow.flowDo.UseModel(&models.Flow{})

	tableName := _flow.flowDo.TableName()
	_flow.ALL = field.NewAsterisk(tableName)
	_flow.Id = field.NewString(tableName, "id")
	_flow.SrcMac = field.NewString(tableName, "src_mac")
	_flow.DstMac = field.NewString(tableName, "dst_mac")
	_flow.SrcIp = field.NewString(tableName, "src_ip")
	_flow.DstIp = field.NewString(tableName, "dst_ip")
	_flow.SrcPort = field.NewUint16(tableName, "src_port")
	_flow.DstPort = field.NewUint16(tableName, "dst_port")
	_flow.IpV = field.NewUint8(tableName, "ipv")
	_flow.TcpFingerprint = field.NewString(tableName, "tcp_fingerprint")
	_flow.SrcOS = field.NewString(tableName, "src_os")
	_flow.DstOS = field.NewString(tableName, "dst_os")
	_flow.Proto = field.NewString(tableName, "proto")
	_flow.SrcCountry = field.NewString(tableName, "src_country")
	_flow.DstCountry = field.NewString(tableName, "dst_country")
	_flow.SrcAS = field.NewString(tableName, "src_as")
	_flow.DstAS = field.NewString(tableName, "dst_as")
	_flow.FirstSeen = field.NewTime(tableName, "first_seen")
	_flow.LastSeen = field.NewTime(tableName, "last_seen")
	_flow.SrcNumPkts = field.NewUint64(tableName, "src_num_pkts")
	_flow.DstNumPkts = field.NewUint64(tableName, "dst_num_pkts")
	_flow.SrcLenPkts = field.NewUint64(tableName, "src_len_pkts")
	_flow.DstLenPkts = field.NewUint64(tableName, "dst_len_pkts")
	_flow.NdpiProto = field.NewString(tableName, "ndpi_proto")
	_flow.NdpiCategory = field.NewString(tableName, "ndpi_category")

	_flow.fillFieldMap()

	return _flow
}

type flow struct {
	flowDo flowDo

	ALL            field.Asterisk
	Id             field.String
	SrcMac         field.String
	DstMac         field.String
	SrcIp          field.String
	DstIp          field.String
	SrcPort        field.Uint16
	DstPort        field.Uint16
	IpV            field.Uint8
	TcpFingerprint field.String
	SrcOS          field.String
	DstOS          field.String
	Proto          field.String
	SrcCountry     field.String
	DstCountry     field.String
	SrcAS          field.String
	DstAS          field.String
	FirstSeen      field.Time
	LastSeen       field.Time
	SrcNumPkts     field.Uint64
	DstNumPkts     field.Uint64
	SrcLenPkts     field.Uint64
	DstLenPkts     field.Uint64
	NdpiProto      field.String
	NdpiCategory   field.String

	fieldMap map[string]field.Expr
}

func (f flow) Table(newTableName string) *flow {
	f.flowDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f flow) As(alias string) *flow {
	f.flowDo.DO = *(f.flowDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *flow) updateTableName(table string) *flow {
	f.ALL = field.NewAsterisk(table)
	f.Id = field.NewString(table, "id")
	f.SrcMac = field.NewString(table, "src_mac")
	f.DstMac = field.NewString(table, "dst_mac")
	f.SrcIp = field.NewString(table, "src_ip")
	f.DstIp = field.NewString(table, "dst_ip")
	f.SrcPort = field.NewUint16(table, "src_port")
	f.DstPort = field.NewUint16(table, "dst_port")
	f.IpV = field.NewUint8(table, "ipv")
	f.TcpFingerprint = field.NewString(table, "tcp_fingerprint")
	f.SrcOS = field.NewString(table, "src_os")
	f.DstOS = field.NewString(table, "dst_os")
	f.Proto = field.NewString(table, "proto")
	f.SrcCountry = field.NewString(table, "src_country")
	f.DstCountry = field.NewString(table, "dst_country")
	f.SrcAS = field.NewString(table, "src_as")
	f.DstAS = field.NewString(table, "dst_as")
	f.FirstSeen = field.NewTime(table, "first_seen")
	f.LastSeen = field.NewTime(table, "last_seen")
	f.SrcNumPkts = field.NewUint64(table, "src_num_pkts")
	f.DstNumPkts = field.NewUint64(table, "dst_num_pkts")
	f.SrcLenPkts = field.NewUint64(table, "src_len_pkts")
	f.DstLenPkts = field.NewUint64(table, "dst_len_pkts")
	f.NdpiProto = field.NewString(table, "ndpi_proto")
	f.NdpiCategory = field.NewString(table, "ndpi_category")

	f.fillFieldMap()

	return f
}

func (f *flow) WithContext(ctx context.Context) IFlowDo { return f.flowDo.WithContext(ctx) }

func (f flow) TableName() string { return f.flowDo.TableName() }

func (f flow) Alias() string { return f.flowDo.Alias() }

func (f flow) Columns(cols ...field.Expr) gen.Columns { return f.flowDo.Columns(cols...) }

func (f *flow) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *flow) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 24)
	f.fieldMap["id"] = f.Id
	f.fieldMap["src_mac"] = f.SrcMac
	f.fieldMap["dst_mac"] = f.DstMac
	f.fieldMap["src_ip"] = f.SrcIp
	f.fieldMap["dst_ip"] = f.DstIp
	f.fieldMap["src_port"] = f.SrcPort
	f.fieldMap["dst_port"] = f.DstPort
	f.fieldMap["ipv"] = f.IpV
	f.fieldMap["tcp_fingerprint"] = f.TcpFingerprint
	f.fieldMap["src_os"] = f.SrcOS
	f.fieldMap["dst_os"] = f.DstOS
	f.fieldMap["proto"] = f.Proto
	f.fieldMap["src_country"] = f.SrcCountry
	f.fieldMap["dst_country"] = f.DstCountry
	f.fieldMap["src_as"] = f.SrcAS
	f.fieldMap["dst_as"] = f.DstAS
	f.fieldMap["first_seen"] = f.FirstSeen
	f.fieldMap["last_seen"] = f.LastSeen
	f.fieldMap["src_num_pkts"] = f.SrcNumPkts
	f.fieldMap["dst_num_pkts"] = f.DstNumPkts
	f.fieldMap["src_len_pkts"] = f.SrcLenPkts
	f.fieldMap["dst_len_pkts"] = f.DstLenPkts
	f.fieldMap["ndpi_proto"] = f.NdpiProto
	f.fieldMap["ndpi_category"] = f.NdpiCategory
}

func (f flow) clone(db *gorm.DB) flow {
	f.flowDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f flow) replaceDB(db *gorm.DB) flow {
	f.flowDo.ReplaceDB(db)
	return f
}

type flowDo struct{ gen.DO }

type IFlowDo interface {
	gen.SubQuery
	Debug() IFlowDo
	WithContext(ctx context.Context) IFlowDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFlowDo
	WriteDB() IFlowDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFlowDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFlowDo
	Not(conds ...gen.Condition) IFlowDo
	Or(conds ...gen.Condition) IFlowDo
	Select(conds ...field.Expr) IFlowDo
	Where(conds ...gen.Condition) IFlowDo
	Order(conds ...field.Expr) IFlowDo
	Distinct(cols ...field.Expr) IFlowDo
	Omit(cols ...field.Expr) IFlowDo
	Join(table schema.Tabler, on ...field.Expr) IFlowDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFlowDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFlowDo
	Group(cols ...field.Expr) IFlowDo
	Having(conds ...gen.Condition) IFlowDo
	Limit(limit int) IFlowDo
	Offset(offset int) IFlowDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFlowDo
	Unscoped() IFlowDo
	Create(values ...*models.Flow) error
	CreateInBatches(values []*models.Flow, batchSize int) error
	Save(values ...*models.Flow) error
	First() (*models.Flow, error)
	Take() (*models.Flow, error)
	Last() (*models.Flow, error)
	Find() ([]*models.Flow, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Flow, err error)
	FindInBatches(result *[]*models.Flow, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Flow) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFlowDo
	Assign(attrs ...field.AssignExpr) IFlowDo
	Joins(fields ...field.RelationField) IFlowDo
	Preload(fields ...field.RelationField) IFlowDo
	FirstOrInit() (*models.Flow, error)
	FirstOrCreate() (*models.Flow, error)
	FindByPage(offset int, limit int) (result []*models.Flow, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFlowDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f flowDo) Debug() IFlowDo {
	return f.withDO(f.DO.Debug())
}

func (f flowDo) WithContext(ctx context.Context) IFlowDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f flowDo) ReadDB() IFlowDo {
	return f.Clauses(dbresolver.Read)
}

func (f flowDo) WriteDB() IFlowDo {
	return f.Clauses(dbresolver.Write)
}

func (f flowDo) Session(config *gorm.Session) IFlowDo {
	return f.withDO(f.DO.Session(config))
}

func (f flowDo) Clauses(conds ...clause.Expression) IFlowDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f flowDo) Returning(value interface{}, columns ...string) IFlowDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f flowDo) Not(conds ...gen.Condition) IFlowDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f flowDo) Or(conds ...gen.Condition) IFlowDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f flowDo) Select(conds ...field.Expr) IFlowDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f flowDo) Where(conds ...gen.Condition) IFlowDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f flowDo) Order(conds ...field.Expr) IFlowDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f flowDo) Distinct(cols ...field.Expr) IFlowDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f flowDo) Omit(cols ...field.Expr) IFlowDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f flowDo) Join(table schema.Tabler, on ...field.Expr) IFlowDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f flowDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFlowDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f flowDo) RightJoin(table schema.Tabler, on ...field.Expr) IFlowDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f flowDo) Group(cols ...field.Expr) IFlowDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f flowDo) Having(conds ...gen.Condition) IFlowDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f flowDo) Limit(limit int) IFlowDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f flowDo) Offset(offset int) IFlowDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f flowDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFlowDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f flowDo) Unscoped() IFlowDo {
	return f.withDO(f.DO.Unscoped())
}

func (f flowDo) Create(values ...*models.Flow) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f flowDo) CreateInBatches(values []*models.Flow, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f flowDo) Save(values ...*models.Flow) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f flowDo) First() (*models.Flow, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Flow), nil
	}
}

func (f flowDo) Take() (*models.Flow, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Flow), nil
	}
}

func (f flowDo) Last() (*models.Flow, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Flow), nil
	}
}

func (f flowDo) Find() ([]*models.Flow, error) {
	result, err := f.DO.Find()
	return result.([]*models.Flow), err
}

func (f flowDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Flow, err error) {
	buf := make([]*models.Flow, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f flowDo) FindInBatches(result *[]*models.Flow, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f flowDo) Attrs(attrs ...field.AssignExpr) IFlowDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f flowDo) Assign(attrs ...field.AssignExpr) IFlowDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f flowDo) Joins(fields ...field.RelationField) IFlowDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f flowDo) Preload(fields ...field.RelationField) IFlowDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f flowDo) FirstOrInit() (*models.Flow, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Flow), nil
	}
}

func (f flowDo) FirstOrCreate() (*models.Flow, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Flow), nil
	}
}

func (f flowDo) FindByPage(offset int, limit int) (result []*models.Flow, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f flowDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f flowDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f flowDo) Delete(models ...*models.Flow) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *flowDo) withDO(do gen.Dao) *flowDo {
	f.DO = *do.(*gen.DO)
	return f
}
