// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q         = new(Query)
	Dashboard *dashboard
	Flow      *flow
	Widget    *widget
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Dashboard = &Q.Dashboard
	Flow = &Q.Flow
	Widget = &Q.Widget
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:        db,
		Dashboard: newDashboard(db, opts...),
		Flow:      newFlow(db, opts...),
		Widget:    newWidget(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Dashboard dashboard
	Flow      flow
	Widget    widget
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Dashboard: q.Dashboard.clone(db),
		Flow:      q.Flow.clone(db),
		Widget:    q.Widget.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Dashboard: q.Dashboard.replaceDB(db),
		Flow:      q.Flow.replaceDB(db),
		Widget:    q.Widget.replaceDB(db),
	}
}

type queryCtx struct {
	Dashboard IDashboardDo
	Flow      IFlowDo
	Widget    IWidgetDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Dashboard: q.Dashboard.WithContext(ctx),
		Flow:      q.Flow.WithContext(ctx),
		Widget:    q.Widget.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
